import Foundation

/// Where a workspace note came from. Mirrors Fantastty's `NoteSource`.
public enum NoteSource: String, Codable, Sendable {
    case terminal   // emitted by the shell/program via an escape sequence
    case user       // typed by the user in the notes panel
    case system     // generated by insanitty
}

/// A prior version of a note's content, kept when the note is edited (edit history).
public struct NoteRevision: Codable, Equatable, Sendable {
    public let content: String
    public let timestamp: Date
    public init(content: String, timestamp: Date) {
        self.content = content
        self.timestamp = timestamp
    }
}

/// A single timestamped note in a workspace's log, with edit history.
public struct WorkspaceNote: Codable, Identifiable, Equatable, Sendable {
    public let id: UUID
    public let timestamp: Date
    public var content: String
    public let tags: [String]
    public let source: NoteSource
    public var revisions: [NoteRevision]

    public init(id: UUID = UUID(), timestamp: Date, content: String,
                tags: [String] = [], source: NoteSource = .user, revisions: [NoteRevision] = []) {
        self.id = id
        self.timestamp = timestamp
        self.content = content
        self.tags = tags
        self.source = source
        self.revisions = revisions
    }

    /// Replace the content, pushing the old content onto the revision history.
    public mutating func updateContent(_ newContent: String, at now: Date) {
        guard newContent != content else { return }
        revisions.append(NoteRevision(content: content, timestamp: now))
        content = newContent
    }
}

/// Persistent per-workspace metadata, keyed by workspace id in `workspaces.json`. Mirrors
/// Fantastty's `SessionMetadata` (notes + archive/trash + active-time + attention + ticket/PR).
public struct WorkspaceMetadata: Codable, Equatable, Sendable {
    public var workspaceID: String
    public var name: String
    public var notes: [WorkspaceNote]
    public var needsAttention: Bool
    public var tags: [String]
    public var isArchived: Bool
    public var archivedAt: Date?
    public var isTrashed: Bool
    public var trashedAt: Date?
    public var ticketURL: String?
    public var pullRequestURL: String?
    public var createdAt: Date
    public var modifiedAt: Date
    /// Cumulative seconds the workspace was actively focused (idle excluded).
    public var totalActiveSeconds: Double

    public init(workspaceID: String, name: String = "", createdAt: Date, modifiedAt: Date,
                notes: [WorkspaceNote] = [], needsAttention: Bool = false, tags: [String] = [],
                isArchived: Bool = false, archivedAt: Date? = nil,
                isTrashed: Bool = false, trashedAt: Date? = nil,
                ticketURL: String? = nil, pullRequestURL: String? = nil,
                totalActiveSeconds: Double = 0) {
        self.workspaceID = workspaceID
        self.name = name
        self.notes = notes
        self.needsAttention = needsAttention
        self.tags = tags
        self.isArchived = isArchived
        self.archivedAt = archivedAt
        self.isTrashed = isTrashed
        self.trashedAt = trashedAt
        self.ticketURL = ticketURL
        self.pullRequestURL = pullRequestURL
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.totalActiveSeconds = totalActiveSeconds
    }

    enum CodingKeys: String, CodingKey {
        case workspaceID, name, notes, needsAttention, tags
        case isArchived, archivedAt, isTrashed, trashedAt, ticketURL, pullRequestURL
        case createdAt, modifiedAt, totalActiveSeconds
    }

    /// Tolerant decode — missing keys fall back to defaults so older files keep loading.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        workspaceID = try c.decode(String.self, forKey: .workspaceID)
        name = try c.decodeIfPresent(String.self, forKey: .name) ?? ""
        notes = try c.decodeIfPresent([WorkspaceNote].self, forKey: .notes) ?? []
        needsAttention = try c.decodeIfPresent(Bool.self, forKey: .needsAttention) ?? false
        tags = try c.decodeIfPresent([String].self, forKey: .tags) ?? []
        isArchived = try c.decodeIfPresent(Bool.self, forKey: .isArchived) ?? false
        archivedAt = try c.decodeIfPresent(Date.self, forKey: .archivedAt)
        isTrashed = try c.decodeIfPresent(Bool.self, forKey: .isTrashed) ?? false
        trashedAt = try c.decodeIfPresent(Date.self, forKey: .trashedAt)
        ticketURL = try c.decodeIfPresent(String.self, forKey: .ticketURL)
        pullRequestURL = try c.decodeIfPresent(String.self, forKey: .pullRequestURL)
        createdAt = try c.decodeIfPresent(Date.self, forKey: .createdAt) ?? Date(timeIntervalSince1970: 0)
        modifiedAt = try c.decodeIfPresent(Date.self, forKey: .modifiedAt) ?? Date(timeIntervalSince1970: 0)
        totalActiveSeconds = try c.decodeIfPresent(Double.self, forKey: .totalActiveSeconds) ?? 0
    }

    /// Append a note and bump modifiedAt.
    public mutating func appendNote(content: String, source: NoteSource = .user, at now: Date) {
        notes.append(WorkspaceNote(timestamp: now, content: content, source: source))
        modifiedAt = now
    }

    /// Set archived state, stamping/clearing archivedAt.
    public mutating func setArchived(_ archived: Bool, at now: Date) {
        isArchived = archived
        archivedAt = archived ? now : nil
        modifiedAt = now
    }

    /// Set trashed state, stamping/clearing trashedAt.
    public mutating func setTrashed(_ trashed: Bool, at now: Date) {
        isTrashed = trashed
        trashedAt = trashed ? now : nil
        modifiedAt = now
    }
}

/// Loads and saves the `workspaceID → WorkspaceMetadata` map to `workspaces.json` (XDG state).
/// On disk it's a JSON array (one object per workspace), matching Fantastty's shape, with ISO-8601
/// dates.
public enum WorkspaceMetadataStore {
    public static func defaultURL(
        environment: [String: String] = ProcessInfo.processInfo.environment,
        home: String = NSHomeDirectory()
    ) -> URL {
        let base = environment["XDG_STATE_HOME"].flatMap { $0.isEmpty ? nil : $0 } ?? "\(home)/.local/state"
        return URL(fileURLWithPath: base).appendingPathComponent("insanitty/workspaces.json")
    }

    private static var encoder: JSONEncoder {
        let e = JSONEncoder()
        e.outputFormatting = [.prettyPrinted, .sortedKeys]
        e.dateEncodingStrategy = .iso8601
        return e
    }
    private static var decoder: JSONDecoder {
        let d = JSONDecoder()
        d.dateDecodingStrategy = .iso8601
        return d
    }

    /// Returns the decoded map (keyed by workspaceID), or empty if missing/unreadable.
    public static func load(from url: URL) -> [String: WorkspaceMetadata] {
        guard let data = try? Data(contentsOf: url),
              let array = try? decoder.decode([WorkspaceMetadata].self, from: data) else { return [:] }
        var map: [String: WorkspaceMetadata] = [:]
        for m in array where !m.workspaceID.isEmpty { map[m.workspaceID] = m }
        return map
    }

    /// Atomically writes the map as a JSON array (stable order by workspaceID).
    public static func save(_ map: [String: WorkspaceMetadata], to url: URL) throws {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        let array = map.values.sorted { $0.workspaceID < $1.workspaceID }
        try encoder.encode(array).write(to: url, options: .atomic)
    }
}
